### ISSUE TITLE
Running using Docker instructions results in libcuda.so.1 missing error

### ISSUE THREAD

**Issue by InconsolableCellist** [openai/gpt-2#204]
```

$ docker build --tag gpt-2 -f Dockerfile.gpu .

...

$ docker run -it gpt-2 bash

...

root@a8c0f508dc92:/gpt-2# export PYTHONIOENCODING=UTF-8
root@a8c0f508dc92:/gpt-2# python3 src/interactive_conditional_samples.py 
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/interactive_conditional_samples.py", line 7, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
root@a8c0f508dc92:/gpt-2# ```

**Comment by InconsolableCellist** [comment]
The docs currently say:

>You can opt to use the --runtime=nvidia flag if you have access to a NVIDIA GPU and a valid install of nvidia-docker 2.0.

This doesn't appear to be optional if you want GPU acceleration. After installing nvidia-docker (though their docs say that GPU support is now built into Docker itself) it seems I have to start docker with:

```
$ docker run --gpus all -it gpt-2 bash  
# pip install -U  tensorflow-gpu==1.14.2
# python3 src/interactive_conditional_samples.py 

```

However that results in 

```

2019-11-08 22:20:58.431974: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcudart.so.10.0'; dlerror: libcudart.so.10.0: cannot open shared object file:
No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/extras/CUPTI/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64                                                                         
2019-11-08 22:20:58.432074: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcublas.so.10.0'; dlerror: libcublas.so.10.0: cannot open shared object file:
No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/extras/CUPTI/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64                                                                         
2019-11-08 22:20:58.432169: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcufft.so.10.0'; dlerror: libcufft.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/extras/CUPTI/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64                                                                           
2019-11-08 22:20:58.432262: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcurand.so.10.0'; dlerror: libcurand.so.10.0: cannot open shared object file:
No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/extras/CUPTI/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64                                                                         
2019-11-08 22:20:58.432353: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcusolver.so.10.0'; dlerror: libcusolver.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/extras/CUPTI/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64                                                                     
2019-11-08 22:20:58.432445: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcusparse.so.10.0'; dlerror: libcusparse.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/extras/CUPTI/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64                          
                                  
2019-11-08 22:20:58.488935: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7                                                        
2019-11-08 22:20:58.489020: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1663] Cannot dlopen some GPU libraries. Skipping registering GPU devices...          
```

**Comment by reterik** [comment]
I think it needs you to be using python 3.6 your codes seem to be outputting 3.5 error codes.  I have seen this error code before "ImportError: libcuda.so.1: cannot open shared object file: No such file or directory" it could also have something to do with which nvidia drivers you are using, but I have yet to troubleshoot this specific package with cuda lib.

**Comment by InconsolableCellist** [comment]
You're correct about the python version. When I enter an interactive bash shell on the container:

```
root@9e5d7d7ceeaa:/gpt-2# python --version
Python 3.5.2
```

This isn't my system version, however, which is 3.7.3.

Isn't docker supposed to fully insulate me from any differences between my host environment and the appropriate deployment environment? How can I run python 3.6 in the docker container?

I have the same questions for the nvidia drivers and cuda library version, I suppose. How do I make my container initialize itself with the proper environment?

**Comment by reterik** [comment]
I have been busy, what setup are you using? OS version? Flavor?

Docker should insulate you from the complexities of the operating system but it is not perfect, virtualenv for python applications is better in my experience.  You could try running virtualenv from the Docker install.  

I would try virtualenv commands I know on Debian/Ubuntu you can run apt-get update from the docker file and then install whatever you want, from Red Hat/CentOS it is yum update then specify which version of python you want to install IE - apt-get install python3.6.

**Comment by InconsolableCellist** [comment]
Thanks for the update. I've tried a large number of versions now, and I've attempted to narrow it down to what seems closest to what gpt-2 was designed with. Currently I'm trying Ubuntu 18.04 with Linux 5.0.0-36. I originally tried tensorflow and tensorflow-gpu=1.13.0 I believe it was, but I've also tried 1.14.0 and 1.15.0. I've installed CUDA and cudnn according to the nvidia directions, but it installs CUDA 10.1, which seems incompatible with tensorflow <= 1.15.0. Also, most docs online seem to want you to use TF >= 2.0 with CUDA 10.1, which I believe doesn't work in the gpt-2 code.

I'm running this all now on a dedicated machine, but what I really need is a list of exactly what versions of everything I need to actually get it to work.

- tensorflow and tensorflow-gpu versions
- python version
- OS version
- Kernel version
- CUDA version
- cudnn version

(Making this especially frustrating is that Nvidia doesn't publish a mapping between CUDA versions and kernel versions, so I was left trying to compile 4.18.0 and 4.15.0 (which shipped with Ubuntu 18.04), but trying to compile the nvidia module for the CUDA 10.0 version resulted in a kernel panic.)

It's a tangled web of incompatible dependencies! I think the docs would greatly benefit from documenting a known-good configuration.

Any help you can offer with a specific configuration would be greatly appreciated.

**Comment by InconsolableCellist** [comment]
After a full day of trial-and-error I have a configuration that works for me: 

- tensorflow and tensorflow-gpu: 1.13.1
- python version: 3.6.8
- OS version: Ubuntu 18.04 HWE
- Kernel version: 4.15.0-70-generic
- CUDA version: 10.0
- cudnn version: 7.6.4 (sept 27th, 2019) for CUDA 10.0

The runfile didn't work, but the .deb did. I had to follow the installation instructions for blacklisting nouveau etc., then install via the deb. Then cudnn, then virtualenv with tf, then I could run gpt-2 and verify it was offloading it to the GPU via the proper libcublas.so.10.0 (which it couldn't find previously)

CUDA: https://developer.nvidia.com/cuda-10.0-download-archive
    instructions: https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html
Cudnn: https://developer.nvidia.com/rdp/cudnn-archive
    instructions: https://docs.nvidia.com/deeplearning/sdk/cudnn-install/index.html
gpt-2 instructions: https://github.com/openai/gpt-2/blob/master/DEVELOPERS.md

I didn't try with docker, so I skipped that section entirely 
I'm also now fine-tuning the model with https://github.com/nshepperd/gpt-2 and also trying https://github.com/minimaxir/gpt-2-simple/blob/master/README.md

**Comment by DillonStreator** [comment]
I ran into the same issue and was able to resolve this by explicitly installing tensorflow inside of the container with:
`pip3 install tensorflow`
